name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # download repository
      - name: Checkout code
        uses: actions/checkout@v3

    # install node environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

    # install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./backend
      
    # add tests

    # build docker image
      - name: Build Docker image
        run: docker build -t the-pipe:${{ github.sha }} .
        working-directory: ./backend

    # run health check
      - name: Health check
        run: |
         docker run -d -p 3001:3001 --name app the-pipe:${{ github.sha }}
         sleep 10
         curl -f http://localhost:3001/health || exit 0   

   # trivy scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'the-pipe:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

   # deploy 
      - name: Deployment step
        run: echo "Deploy step handled by render auto-deploy"
